[testServer]

BROKER_HOST = 100.77.143.54
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = testExchange
QUEUE = testQueue
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[testDMZ]

BROKER_HOST = 100.77.143.54
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = dmzExchange
QUEUE = dmzQueue
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[testdev]

BROKER_HOST = 100.77.143.54
BROKER_PORT = 5672
USER = devadmin
PASSWORD = it490
VHOST = devHost
EXCHANGE = devExchange
QUEUE = devQueue
; EXCHANGE_TYPE = ????
AUTO_DELETE = true

[devDMZ]
; files that need this instead of testdev: DMZ/dmzListenerV2.php and searchBar.php
BROKER_HOST = 100.77.143.54
BROKER_PORT = 5672
USER = devadmin
PASSWORD = it490
VHOST = devHost
EXCHANGE = dmzExchange
QUEUE = dmzQueue
; EXCHANGE_TYPE = ????
AUTO_DELETE = true
